### ISSUE TITLE
Unable to load plugin heroku-pg-extras (undefined method error)

### ISSUE THREAD

**Issue by aaroncraigongithub** [heroku/heroku-pg-extras#112]
```
$ heroku plugins:install git://github.com/heroku/heroku-pg-extras.git
Installing git://github.com/heroku/heroku-pg-extras.git... failed

 !    Unable to load plugin heroku-pg-extras.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)
    Command:     heroku plugins:install git://github.com/heroku/heroku-pg-extras.git
    Plugins:     heroku-accounts
                 heroku-pg-extras
                 heroku-repo

    Version:     heroku-toolbelt/3.34.0 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    96700afa3903495493a8aed63574e46f
```

```
$ cat ~/.heroku/error.log
Unable to load plugin heroku-pg-extras.
undefined method `configure_addon' for class `Heroku::Command::Addons'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:790:in `alias_method'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:790:in `<class:Addons>'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:789:in `<module:Command>'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:788:in `<top (required)>'
/usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/aaron/.heroku/plugins/heroku-pg-extras/init.rb:6:in `<top (required)>'
/Users/aaron/.heroku/client/lib/heroku/plugin.rb:62:in `load'
/Users/aaron/.heroku/client/lib/heroku/plugin.rb:62:in `load_plugin'
/Users/aaron/.heroku/client/lib/heroku/command/plugins.rb:120:in `block in ruby_plugin_install'
/Users/aaron/.heroku/client/lib/heroku/helpers.rb:258:in `action'
/Users/aaron/.heroku/client/lib/heroku/command/plugins.rb:117:in `ruby_plugin_install'
/Users/aaron/.heroku/client/lib/heroku/command/plugins.rb:47:in `install'
/Users/aaron/.heroku/client/lib/heroku/command.rb:223:in `run'
/Users/aaron/.heroku/client/lib/heroku/cli.rb:45:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

```
$ heroku version
heroku-toolbelt/3.34.0 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-accounts
heroku-repo
```

**Comment by will** [comment]
Just pushed a fix, can you try again?

**Comment by fmorton** [comment]
I just had the same problem after your last fix:

 !    Unable to load plugin heroku-pg-extras.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)
    Command:     heroku config:set BUNDLE_WITHOUT=development:test
    Plugins:     heroku-pg-extras
    Version:     heroku-toolbelt/3.34.0 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    eeae69c040e74da5889a1f977ee22821

**Comment by will** [comment]
did you update the plugin? the last fix completely removed any mentions of `configure_addon` https://github.com/heroku/heroku-pg-extras/commit/cafe0d9749cef54206b40d5b6a655f2dd25f2446

**Comment by aaroncraigongithub** [comment]
Working for me now.

**Comment by will** [comment]
cool

**Comment by fmorton** [comment]
Attempted to update the plugin. Failed again the first time with the same issue. Did it again just for kicks and worked fine. All looks good now. Thanks for the quick fix.

**Comment by will** [comment]
Yeah that makes sense. When there are errors in plugins, it tells you about them with that message, and then doesn't load the plugin, and continues on. So you'd see the error one more time when running `heroku plugins:update`
