### ISSUE TITLE
heroku-pg-extras install is failing

### ISSUE THREAD

**Issue by spollack** [heroku/heroku-pg-extras#113]
I previously had this plugin installed successfully. today, it started giving me errors when running any command. So i removed the plugin and tried to re-install it. now it won't install either. 

```
heroku plugins:install git://github.com/heroku/heroku-pg-extras.git
Installing git://github.com/heroku/heroku-pg-extras.git... failed

 !    Unable to load plugin heroku-pg-extras.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)
    Command:     heroku plugins:install git://github.com/heroku/heroku-pg-extras.git
    Plugins:     heroku-pg-extras
                 heroku-repo

    Version:     heroku-toolbelt/3.34.0 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    26abe1b665644eb18623e3d6a6b24a9b


    More information in /Users/spollack/.heroku/error.log

```

here are the lines from the error.log file:
```
Unable to load plugin heroku-pg-extras.
undefined method `configure_addon' for class `Heroku::Command::Addons'
/Users/spollack/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:790:in `alias_method'
/Users/spollack/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:790:in `<class:Addons>'
/Users/spollack/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:789:in `<module:Command>'
/Users/spollack/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:788:in `<top (required)>'
/usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/Users/spollack/.heroku/plugins/heroku-pg-extras/init.rb:6:in `<top (required)>'
/Users/spollack/.heroku/client/lib/heroku/plugin.rb:62:in `load'
/Users/spollack/.heroku/client/lib/heroku/plugin.rb:62:in `load_plugin'
/Users/spollack/.heroku/client/lib/heroku/command/plugins.rb:120:in `block in ruby_plugin_install'
/Users/spollack/.heroku/client/lib/heroku/helpers.rb:258:in `action'
/Users/spollack/.heroku/client/lib/heroku/command/plugins.rb:117:in `ruby_plugin_install'
/Users/spollack/.heroku/client/lib/heroku/command/plugins.rb:47:in `install'
/Users/spollack/.heroku/client/lib/heroku/command.rb:223:in `run'
/Users/spollack/.heroku/client/lib/heroku/cli.rb:45:in `start'
/usr/bin/heroku:24:in `<main>'
```

you'll note that it thinks the plugin is installed from the above output, but it won't run, the extra commands are not available. 

help?

**Comment by will** [comment]
Just pushed a fix, can you try again?

**Comment by spollack** [comment]
the fix worked, thank you for the fast response!
